ingressController:
  installCRDs: false

proxy:
  type: LoadBalancer
  annotations:
    # these annotations are from Kubernetes in-tree, not AWS load balancer controller.
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

env:
  trusted_ips: 0.0.0.0/0,::0
  real_ip_recursive: "on"
  real_ip_header: X-Forwarded-For
